version: '3'
services:
  Credit_Worthiness:
    env_file: .env
    container_name: Credit_Worthiness
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}